/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CampingSpaceService } from "../campingSpace.service";
import { CampingSpaceCreateInput } from "./CampingSpaceCreateInput";
import { CampingSpace } from "./CampingSpace";
import { CampingSpaceFindManyArgs } from "./CampingSpaceFindManyArgs";
import { CampingSpaceWhereUniqueInput } from "./CampingSpaceWhereUniqueInput";
import { CampingSpaceUpdateInput } from "./CampingSpaceUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class CampingSpaceControllerBase {
  constructor(protected readonly service: CampingSpaceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CampingSpace })
  async createCampingSpace(
    @common.Body() data: CampingSpaceCreateInput
  ): Promise<CampingSpace> {
    return await this.service.createCampingSpace({
      data: data,
      select: {
        available: true,
        createdAt: true,
        description: true,
        id: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CampingSpace] })
  @ApiNestedQuery(CampingSpaceFindManyArgs)
  async campingSpaces(@common.Req() request: Request): Promise<CampingSpace[]> {
    const args = plainToClass(CampingSpaceFindManyArgs, request.query);
    return this.service.campingSpaces({
      ...args,
      select: {
        available: true,
        createdAt: true,
        description: true,
        id: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CampingSpace })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async campingSpace(
    @common.Param() params: CampingSpaceWhereUniqueInput
  ): Promise<CampingSpace | null> {
    const result = await this.service.campingSpace({
      where: params,
      select: {
        available: true,
        createdAt: true,
        description: true,
        id: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CampingSpace })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCampingSpace(
    @common.Param() params: CampingSpaceWhereUniqueInput,
    @common.Body() data: CampingSpaceUpdateInput
  ): Promise<CampingSpace | null> {
    try {
      return await this.service.updateCampingSpace({
        where: params,
        data: data,
        select: {
          available: true,
          createdAt: true,
          description: true,
          id: true,
          location: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CampingSpace })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCampingSpace(
    @common.Param() params: CampingSpaceWhereUniqueInput
  ): Promise<CampingSpace | null> {
    try {
      return await this.service.deleteCampingSpace({
        where: params,
        select: {
          available: true,
          createdAt: true,
          description: true,
          id: true,
          location: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: CampingSpaceWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        camper: {
          select: {
            id: true,
          },
        },

        campingSpace: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: CampingSpaceWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateCampingSpace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: CampingSpaceWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateCampingSpace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: CampingSpaceWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateCampingSpace({
      where: params,
      data,
      select: { id: true },
    });
  }
}
