/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CamperService } from "../camper.service";
import { CamperCreateInput } from "./CamperCreateInput";
import { Camper } from "./Camper";
import { CamperFindManyArgs } from "./CamperFindManyArgs";
import { CamperWhereUniqueInput } from "./CamperWhereUniqueInput";
import { CamperUpdateInput } from "./CamperUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class CamperControllerBase {
  constructor(protected readonly service: CamperService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Camper })
  async createCamper(@common.Body() data: CamperCreateInput): Promise<Camper> {
    return await this.service.createCamper({
      data: data,
      select: {
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Camper] })
  @ApiNestedQuery(CamperFindManyArgs)
  async campers(@common.Req() request: Request): Promise<Camper[]> {
    const args = plainToClass(CamperFindManyArgs, request.query);
    return this.service.campers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Camper })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async camper(
    @common.Param() params: CamperWhereUniqueInput
  ): Promise<Camper | null> {
    const result = await this.service.camper({
      where: params,
      select: {
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Camper })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCamper(
    @common.Param() params: CamperWhereUniqueInput,
    @common.Body() data: CamperUpdateInput
  ): Promise<Camper | null> {
    try {
      return await this.service.updateCamper({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          fullName: true,
          id: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Camper })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCamper(
    @common.Param() params: CamperWhereUniqueInput
  ): Promise<Camper | null> {
    try {
      return await this.service.deleteCamper({
        where: params,
        select: {
          createdAt: true,
          email: true,
          fullName: true,
          id: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: CamperWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        camper: {
          select: {
            id: true,
          },
        },

        campingSpace: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: CamperWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateCamper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: CamperWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateCamper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: CamperWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateCamper({
      where: params,
      data,
      select: { id: true },
    });
  }
}
